// SVG Components Export
export { default as ChevronUp } from '../../assets/icons/chevron-up.svg';
export { default as ChevronDown } from '../../assets/icons/chevron-down.svg';
export { default as ChevronLeft } from '../../assets/icons/chevron-left.svg';
export { default as ChevronRight } from '../../assets/icons/chevron-right.svg';
export { default as Google } from '../../assets/icons/google.svg';
export { default as Apple } from '../../assets/icons/apple.svg';
export { default as Camera } from '../../assets/icons/camera.svg';
export { default as OutlineCamera } from '../../assets/icons/camera-outline.svg';
export { default as Home } from '../../assets/icons/home.svg';
export { default as Search } from '../../assets/icons/search.svg';
export { default as Settings } from '../../assets/icons/settings.svg';
export { default as Close } from '../../assets/icons/close.svg';
export { default as Eye } from '../../assets/icons/eye.svg';
export { default as EyeOff } from '../../assets/icons/eye-off.svg';
export { default as ArrowRight } from '../../assets/icons/arrow-right.svg';
export { default as Scan } from '../../assets/icons/scan.svg';
export { default as Heart } from '../../assets/icons/heart fill.svg';
export { default as Notification } from '../../assets/icons/notification.svg';
export { default as More } from '../../assets/icons/more.svg';
export { default as Favorite } from '../../assets/icons/favorite.svg';
export { default as Archive } from '../../assets/icons/archive.svg';
export { default as Gallery } from '../../assets/icons/gallery.svg';
export { default as Premium } from '../../assets/icons/premium.svg';
export { default as Goal } from '../../assets/icons/goal.svg';
export { default as Calories } from '../../assets/icons/calories.svg';
export { default as Protein } from '../../assets/icons/protein.svg';
export { default as Carbs } from '../../assets/icons/carbs.svg';
export { default as Fat } from '../../assets/icons/fat.svg';
export { default as Analysis } from '../../assets/icons/analysis.svg';

export { default as Diets } from '../../assets/icons/diets.svg';
export { default as AI } from '../../assets/icons/ai.svg';
export { default as Tick } from '../../assets/icons/tick.svg';
export { default as TickCircle } from '../../assets/icons/tick-circle.svg';
export { default as Visa } from '../../assets/icons/visa.svg';
export { default as ApplePay } from '../../assets/icons/applepay.svg';
export { default as GooglePay } from '../../assets/icons/googlepay.svg';
